cp

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -28,12 +28,12 @@ die() {
   exit "$code"
 }
 
-_validate_script_location() {
+validate_script_location() {
   # Ensure script is located within the dotfiles directory 
   [[ !"${BASH_SOURCE[0]}" =~ "$DOTFILES_DIR" ]] || die "Script must be located within: $DOTFILES_DIR"
 }
 
-_run_stow() {
+run_stow() {
   # Stow commands: https://www.gnu.org/software/stow/manual/html_node/Invoking-Stow.html
   # Notes:
   #  -v : verbose
@@ -46,7 +46,7 @@ _run_stow() {
   # Change to dotfiles directory 
   cd "$DOTFILES_DIR" || die "Could not change directory to $DOTFILES_DIR"
 
-  EXCLUDE="ansible bin scripts vscode"
+  EXCLUDE="ansible bin scripts"
   PACKAGES_TO_STOW=()
   for pkg in */; do
     # Remove the trailing slash for the directory name
@@ -73,18 +73,6 @@ _run_stow() {
   echo "Stow Complete"
 }
 
-_validate_script_location
-
-while [[ "$#" -gt 0 ]]; do
-  case "${1-}" in
-    -h|--help) usage ;;
-    -v|--verbose) set -x ;;
-    stow) shift; _run_stow "$@"; exit ;;
-    -*) die "Error: Unknown option ${1-}" ;;
-    *) POSITIONAL_ARGS+=("${1-}") ;;
-  esac
-  shift
-done
 
 detect_os() {
   if [ -f /etc/os-release ]; then
@@ -95,69 +83,101 @@ detect_os() {
   fi
 }
 
-function macos_setup() {
+macos_setup() {
   if ! [ -x "$(command -v brew)" ]; then
     echo "Installing Homebrew"
-    /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   fi
   if ! [ -x "$(command -v ansible)" ]; then
     echo "Installing Ansible"
-    _cmd "brew install ansible"
+    brew install ansible
   fi
   if ! [ -x "$(command -v git)" ]; then
     echo "Installing Git"
-    _cmd "brew install git"
+    brew install git
+  fi
+  if ! [ -x "$(command -v stow)" ]; then
+    echo "Installing GNU Stow"
+    brew install stow
   fi
 }
 
-function ubuntu_setup() {
-    echo "ubuntu setup...do nothing"
+ubuntu_setup() {
+  echo "ubuntu setup...do nothing"
 }
 
-function arch_setup() {
-    echo "arch setup...do nothing"
+arch_setup() {
+  echo "arch setup...do nothing"
 }
 
-dotfiles_os=$(detect_os)
-echo "Loading Setup for detected OS: $dotfiles_os"
-case $dotfiles_os in
-  ubuntu)
-    ubuntu_setup
-    ;;
-  arch)
-    arch_setup
-    ;;
-  darwin)
-    macos_setup
-    ;;
-  *)
-    echo 'Unsupported OS'
-    ;;
-esac
+parse_args() {
+  POSITIONAL_ARGS=()
+  while [[ "$#" -gt 0 ]]; do
+    case "${1-}" in
+      -h|--help) usage ;;
+      -v|--verbose) set -x ;;
+      stow) shift; run_stow "$@"; exit ;;
+      -*) die "Error: Unknown option ${1-}" ;;
+      *) POSITIONAL_ARGS+=("${1-}") ;;
+    esac
+    shift
+  done
+}
 
-# Generate SSH keys
-if ! [[ -f "$SSH_DIR/authorized_keys" ]]; then
-  mkdir -p "$SSH_DIR"
-  chmod 700 "$SSH_DIR"
+os_setup() {
+  dotfiles_os=$(detect_os)
+  echo "Loading Setup for detected OS: $dotfiles_os"
+  case $dotfiles_os in
+    ubuntu)
+      ubuntu_setup
+      ;;
+    arch)
+      arch_setup
+      ;;
+    darwin)
+      macos_setup
+      ;;
+    *)
+      echo 'Unsupported OS'
+      ;;
+  esac
+}
 
-  ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N "" -C "$USER@$HOSTNAME"
+provision_ssh_keys() {
+  # Generate SSH keys
+  if ! [[ -f "$SSH_DIR/authorized_keys" ]]; then
+    mkdir -p "$SSH_DIR"
+    chmod 700 "$SSH_DIR"
 
-  cat "$SSH_DIR/id_ed25519.pub" >> "$SSH_DIR/authorized_keys"
-  chmod 600 "$SSH_DIR/authorized_keys"
+    ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N "" -C "$USER@$HOSTNAME"
+
+    cat "$SSH_DIR/id_ed25519.pub" >> "$SSH_DIR/authorized_keys"
+    chmod 600 "$SSH_DIR/authorized_keys"
+  fi
+}
+
+run_ansible_playbook() {
+  echo "Running ansible playbook"
+
+  ANSIBLE_DIR="$DOTFILES_DIR/ansible"
+  ANSIBLE_MAIN_PATH=${ANSIBLE_DIR}/main.yml
+  ANSIBLE_CONFIG_PATH=${ANSIBLE_DIR}/ansible.cfg
+  ANSIBLE_REQ_PATH=${ANSIBLE_DIR}/requirements/common.yml
+
+  ANSIBLE_CONFIG=$ANSIBLE_CONFIG_PATH ansible-galaxy install -r $ANSIBLE_REQ_PATH
+  ANSIBLE_CONFIG=$ANSIBLE_CONFIG_PATH ansible-playbook $ANSIBLE_MAIN_PATH "$@"
+}
+
+main() {
+  echo "running main()..."
+
+  validate_script_location 
+  parse_args "$@"
+  os_setup
+  provision_ssh_keys
+  run_ansible_playbook "$@"
+}
+
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  main "$@"
 fi
-
-if ! [ -x "$(command -v ansible)" ]; then
-    echo "Ansible not found. Please install manually."
-    exit 1
-fi
-
-echo "Running ansible playbook"
-
-ANSIBLE_DIR="$DOTFILES_DIR/ansible"
-ANSIBLE_MAIN_PATH=${ANSIBLE_DIR}/main.yml
-ANSIBLE_CONFIG_PATH=${ANSIBLE_DIR}/ansible.cfg
-ANSIBLE_REQ_PATH=${ANSIBLE_DIR}/requirements/common.yml
-
-ANSIBLE_CONFIG=$ANSIBLE_CONFIG_PATH ansible-galaxy install -r $ANSIBLE_REQ_PATH
-ANSIBLE_CONFIG=$ANSIBLE_CONFIG_PATH ansible-playbook $ANSIBLE_MAIN_PATH "$@"
-
